import type { ForumComment, Post, Profile } from '../types/forum';

const now = Date.now();

export const mockProfiles: Profile[] = [
  {
    id: 'demo-admin@inuni.local',
    username: 'admin',
    displayName: 'InUni Moderator',
    role: 'admin',
    isBanned: false,
    banReason: null,
    isUctVerified: false,
    createdAt: new Date(now - 1000 * 60 * 60 * 24 * 90).toISOString(),
  },
  {
    id: 'mock-user-a',
    username: 'maya',
    displayName: 'Maya',
    role: 'student',
    isBanned: false,
    banReason: null,
    isUctVerified: true,
    createdAt: new Date(now - 1000 * 60 * 60 * 24 * 30).toISOString(),
  },
  {
    id: 'mock-user-b',
    username: 'liam',
    displayName: 'Liam',
    role: 'student',
    isBanned: false,
    banReason: null,
    isUctVerified: true,
    createdAt: new Date(now - 1000 * 60 * 60 * 24 * 20).toISOString(),
  },
  {
    id: 'mock-user-d',
    username: 'nandi',
    displayName: 'Nandi',
    role: 'student',
    isBanned: false,
    banReason: null,
    isUctVerified: false,
    createdAt: new Date(now - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
  {
    id: 'mock-user-e',
    username: 'ari',
    displayName: 'Ari',
    role: 'student',
    isBanned: false,
    banReason: null,
    isUctVerified: true,
    createdAt: new Date(now - 1000 * 60 * 60 * 24 * 8).toISOString(),
  },
  {
    id: 'mock-user-f',
    username: 'sam',
    displayName: 'Sam',
    role: 'student',
    isBanned: false,
    banReason: null,
    isUctVerified: true,
    createdAt: new Date(now - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: 'mock-user-g',
    username: 'jules',
    displayName: 'Jules',
    role: 'student',
    isBanned: false,
    banReason: null,
    isUctVerified: false,
    createdAt: new Date(now - 1000 * 60 * 60 * 24 * 6).toISOString(),
  },
];

export const mockPosts: Post[] = [
  {
    id: 'mock-study-notes',
    title: 'Best way to organize notes before finals?',
    category: 'Academics',
    content:
      'I am trying to stop keeping everything in one giant doc. What study systems are working for everyone this semester?',
    authorId: 'mock-user-a',
    authorName: 'Maya',
    authorIsUctVerified: true,
    isAnonymous: false,
    createdAt: new Date(now - 1000 * 60 * 38).toISOString(),
    commentCount: 2,
  },
  {
    id: 'mock-campus-coffee',
    title: 'Quiet places on campus after 6pm',
    category: 'Campus Life',
    content:
      'The library gets crowded after lectures. Are there any calm spaces where people can study without needing a booking?',
    authorId: 'mock-user-b',
    authorName: 'Liam',
    authorIsUctVerified: true,
    isAnonymous: false,
    createdAt: new Date(now - 1000 * 60 * 60 * 5).toISOString(),
    commentCount: 1,
  },
  {
    id: 'mock-csc-recursion',
    title: 'CSC1016S test 2 prep: recursion questions?',
    category: 'Academics',
    content:
      'I understand the lecture examples but still freeze when the question changes. Any good way to practise trace tables before the test?',
    authorId: 'mock-user-e',
    authorName: 'Ari',
    authorIsUctVerified: true,
    isAnonymous: false,
    createdAt: new Date(now - 1000 * 60 * 26).toISOString(),
    commentCount: 3,
  },
  {
    id: 'mock-jammie-delay',
    title: 'Jammie shuttle timing after 5pm',
    category: 'Campus Life',
    content:
      'The lower campus stop has felt unpredictable this week. Is there a better route when lectures finish late?',
    authorId: 'mock-user-g',
    authorName: 'Jules',
    authorIsUctVerified: false,
    isAnonymous: false,
    createdAt: new Date(now - 1000 * 60 * 55).toISOString(),
    commentCount: 0,
  },
  {
    id: 'mock-r50-lunch',
    title: 'What can I buy for lunch with R50 on upper campus?',
    category: 'Questions',
    content:
      'Trying to avoid spending too much between lectures. Anything filling that is usually under R50?',
    authorId: 'mock-user-f',
    authorName: 'Sam',
    authorIsUctVerified: true,
    isAnonymous: false,
    createdAt: new Date(now - 1000 * 60 * 60 * 2).toISOString(),
    commentCount: 2,
  },
  {
    id: 'mock-dp-rules',
    title: 'Can DP rules change after the handbook is published?',
    category: 'Academics',
    content:
      'One course announcement sounds different from the handbook. Has anyone dealt with this before?',
    authorId: 'mock-user-b',
    authorName: 'Liam',
    authorIsUctVerified: true,
    isAnonymous: false,
    createdAt: new Date(now - 1000 * 60 * 60 * 8).toISOString(),
    commentCount: 1,
  },
  {
    id: 'mock-confession',
    title: 'I changed majors and feel behind',
    category: 'Confessions',
    content:
      'Everyone else seems to know exactly what they are doing. I know switching was right, but starting again is harder than I expected.',
    authorId: 'mock-user-c',
    authorName: 'Anonymous',
    authorIsUctVerified: true,
    isAnonymous: true,
    createdAt: new Date(now - 1000 * 60 * 60 * 22).toISOString(),
    commentCount: 0,
  },
  {
    id: 'mock-lost-calculator',
    title: 'Lost calculator near the engineering labs',
    category: 'Lost & Found',
    content:
      'I found a black Casio calculator outside Lab 3. Message the lab assistant with the model number and sticker on the back.',
    authorId: 'mock-user-d',
    authorName: 'Nandi',
    authorIsUctVerified: false,
    isAnonymous: false,
    createdAt: new Date(now - 1000 * 60 * 60 * 30).toISOString(),
    commentCount: 1,
  },
];

export const mockComments: ForumComment[] = [
  {
    id: 'mock-comment-1',
    postId: 'mock-study-notes',
    authorId: 'mock-user-e',
    authorName: 'Ari',
    authorIsUctVerified: true,
    content: 'I use one page per lecture and a weekly recap page. It keeps revision much less chaotic.',
    createdAt: new Date(now - 1000 * 60 * 24).toISOString(),
  },
  {
    id: 'mock-comment-2',
    postId: 'mock-study-notes',
    authorId: 'mock-user-f',
    authorName: 'Sam',
    authorIsUctVerified: true,
    content: 'Try active recall questions at the bottom of each topic. Future-you will be grateful.',
    createdAt: new Date(now - 1000 * 60 * 13).toISOString(),
  },
  {
    id: 'mock-comment-3',
    postId: 'mock-campus-coffee',
    authorId: 'mock-user-g',
    authorName: 'Jules',
    authorIsUctVerified: false,
    content: 'The education building has open tables near the second-floor windows most evenings.',
    createdAt: new Date(now - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: 'mock-comment-5',
    postId: 'mock-csc-recursion',
    authorId: 'mock-user-a',
    authorName: 'Maya',
    authorIsUctVerified: true,
    content: 'Write down the base case first, then trace the smallest input by hand before touching the general case.',
    createdAt: new Date(now - 1000 * 60 * 20).toISOString(),
  },
  {
    id: 'mock-comment-6',
    postId: 'mock-csc-recursion',
    authorId: 'mock-user-b',
    authorName: 'Liam',
    authorIsUctVerified: true,
    content: 'The past prac questions on nested lists helped me more than rereading the slides.',
    createdAt: new Date(now - 1000 * 60 * 16).toISOString(),
  },
  {
    id: 'mock-comment-7',
    postId: 'mock-csc-recursion',
    authorId: 'mock-user-f',
    authorName: 'Sam',
    authorIsUctVerified: true,
    content: 'Try explaining each stack frame out loud. It sounds awkward but catches mistakes quickly.',
    createdAt: new Date(now - 1000 * 60 * 11).toISOString(),
  },
  {
    id: 'mock-comment-8',
    postId: 'mock-r50-lunch',
    authorId: 'mock-user-d',
    authorName: 'Nandi',
    authorIsUctVerified: false,
    content: 'Soup and a roll is usually the safest filling option when it is available.',
    createdAt: new Date(now - 1000 * 60 * 42).toISOString(),
  },
  {
    id: 'mock-comment-9',
    postId: 'mock-r50-lunch',
    authorId: 'mock-user-e',
    authorName: 'Ari',
    authorIsUctVerified: true,
    content: 'If you have a microwave later, the Food tool budget scanner is also useful for planning around that number.',
    createdAt: new Date(now - 1000 * 60 * 36).toISOString(),
  },
  {
    id: 'mock-comment-10',
    postId: 'mock-dp-rules',
    authorId: 'mock-user-a',
    authorName: 'Maya',
    authorIsUctVerified: true,
    content: 'Ask the course convenor to confirm it in writing. The faculty office can help if the wording conflicts.',
    createdAt: new Date(now - 1000 * 60 * 60 * 7).toISOString(),
  },
  {
    id: 'mock-comment-4',
    postId: 'mock-lost-calculator',
    authorId: 'mock-user-h',
    authorName: 'Theo',
    authorIsUctVerified: true,
    content: 'Thanks for posting this here. Lost and found at the main desk is also worth checking.',
    createdAt: new Date(now - 1000 * 60 * 60 * 20).toISOString(),
  },
];
